name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create public directory
      run: mkdir public

    - name: Copy HTML projects
      run: |
        for dir in $(ls -d */ | grep -v '^\.'); do
          if [ "$dir" != "public/" ]; then
            cp -r $dir public/
          fi
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public